#pragma once

enum CacheType {
	STMT_STMT, STMT_PROGLINE, STMT_READ, STMT_PRINT, STMT_CALL, STMT_WHILE, STMT_IF, STMT_ASSIGN, STMT_SWITCH,
	PROGLINE_STMT, PROGLINE_PROGLINE, PROGLINE_READ, PROGLINE_PRINT, PROGLINE_CALL, PROGLINE_WHILE, PROGLINE_IF, PROGLINE_ASSIGN, PROGLINE_SWITCH,
	READ_STMT, READ_PROGLINE, READ_READ, READ_PRINT, READ_CALL, READ_WHILE, READ_IF, READ_ASSIGN, READ_SWITCH,
	PRINT_STMT, PRINT_PROGLINE, PRINT_READ, PRINT_PRINT, PRINT_CALL, PRINT_WHILE, PRINT_IF, PRINT_ASSIGN, PRINT_SWITCH,
	CALL_STMT, CALL_PROGLINE, CALL_READ, CALL_PRINT, CALL_CALL, CALL_WHILE, CALL_IF, CALL_ASSIGN, CALL_SWITCH,
	WHILE_STMT, WHILE_PROGLINE, WHILE_READ, WHILE_PRINT, WHILE_CALL, WHILE_WHILE, WHILE_IF, WHILE_ASSIGN, WHILE_SWITCH,
	IF_STMT, IF_PROGLINE, IF_READ, IF_PRINT, IF_CALL, IF_WHILE, IF_IF, IF_ASSIGN, IF_SWITCH,
	ASSIGN_STMT, ASSIGN_PROGLINE, ASSIGN_READ, ASSIGN_PRINT, ASSIGN_CALL, ASSIGN_WHILE, ASSIGN_IF, ASSIGN_ASSIGN, ASSIGN_SWITCH,
	SWITCH_STMT, SWITCH_PROGLINE, SWITCH_READ, SWITCH_PRINT, SWITCH_CALL, SWITCH_WHILE, SWITCH_IF, SWITCH_ASSIGN, SWITCH_SWITCH
};