#pragma once

enum Type {
	STATEMENT, PROGLINE, READ, PRINT, CALL, WHILE, IF, ASSIGN, VARIABLE, CONSTANT, PROCEDURE, BOOLEAN, UNDERSCORE, FIXED, PATTERN_EXACT, PATTERN_SUB, WITH_STRING, WITH_INTEGER, INVALID
};